### PR TITLE
Dart Refactor Part 1

### PR DESCRIPTION
**Pull request by seendsouza**
`add` command and `data_type` subcommand added just so that the commands made after this can be made in the same fashion

### CODE REVIEW

**Comment by seendsouza** [comment]
Ignore that Codacy Review, since it doesn't support Dart.

**Review by Kirbydude27 — APPROVED** [review]
Looks fine. Bye Python

**Review by jeffrey-dot-li — APPROVED** [review]
How are dividing what goes into bin/lib folders? other than that its good

**Comment by seendsouza** [comment]
@DrCheddar there's a lib/src/commands folder with all the commands, and then individual folders in lib/src representing each command. Check the pull request on vscout-docs for commands (and attempt to roast it while ur at it)

**Pull request merged**
